### ISSUE TITLE
New add on request

### ISSUE THREAD

**Issue by atulsian89** [eunas/essentials#1]
Hi Eunas,

I have been using your script to make my installs simpler.

Is it possible to add an option to install blog (Ghost,wordpress)? I am sorry if this request shouldn't be here. I was not sure how to contact you for this request.

Thanks in advance.

**Comment by eunas** [comment]
Yeah shouldn't be a problem. I'll look into when i get the time.

**Comment by atulsian89** [comment]
Thank you so much. I will wait.  

Ghost blog with nginx and node.js would be awesome. 

Regards.

**Comment by eunas** [comment]
I updated the script to install Ghost and node.js with Nginx as reverse proxy.
Currently it's installed with SQLite as the database, I'll add the option to choose between SQLite and MySQL soon.
Wordpress install will be next.

Please test it, and let me know how it works.

**Comment by atulsian89** [comment]
Cool. Thank you so much....

Just to confirm does this work on nat vps? I am reimaging my VPS to check the setup. Will let you know if i get any errors.

**Comment by eunas** [comment]
I haven't tested it on a nat VPS yet. But I don't see why it shouldn't

**Comment by atulsian89** [comment]
It works really great.

I am curious to know why was the default ghost folder was move to other folder instead of using "/var/www/" folder? 

I will be testing it on NAT VPS soon.

**Comment by eunas** [comment]
Not for any particular reason really. It's just easier for me to remember the paths, since most of the programs are placed there, Transmission, aria, nginx, ghost and so on.

Unless you already figured it out, it's in /usr/share/ghost

**Comment by eunas** [comment]
Both requests has been added. Please open a new issue if there are any problems.
