### ISSUE TITLE
bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by nospy** [eunas/essentials#2]
It seems that setup.sh has an issue related to dos line ending file.
I was able to resolve this problem by following this guide:
:set fileformat=unix
Finally save it

:x! or :wq!

http://stackoverflow.com/a/5514351

**Comment by eunas** [comment]
It's caused by the file being saved with Windows line endings. I re-uploaded the file using the Unix line endings instead.
So the issue should be resolved.

Thanks for reporting it. I been real busy lately and haven't really been using the script.
